name: Documentation
description: Improvements or additions to documentation
labels: ["documentation"]
body:
  - attributes:
      description: Describe the documentation issue or improvement.
      label: Documentation Issue
    id: documentation
    type: textarea
    validations:
      required: true
