name: Documentation
description: Improvements or additions to documentation
labels: ["documentation"]
body:
  - type: textarea
    id: documentation
    attributes:
      label: Documentation Issue
      description: Describe the documentation issue or improvement.
    validations:
      required: true
