name: Feature Request
description: Suggest an idea for this project
labels: ["feature request"]
body:
  - attributes:
      description: A clear and concise description of what the feature is.
      label: Description
      placeholder: Describe the feature here...
    id: description
    type: textarea
    validations:
      required: true
