name: Question
description: Ask a question
labels: ["question"]
body:
  - attributes:
      description: What is your question?
      label: Question
    id: question
    type: textarea
    validations:
      required: true
