name: CI

on:
  pull_request:
    branches:
      - main
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 23

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint:ci

      - name: Typecheck
        run: npm run typecheck

      - name: Spellcheck
        run: npm run spellcheck:ci

  test:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build:ci

      - name: Install tailwindcss v3
        run: npm run install:v3
        
      - name: Run tests with tailwindcss v3
        run: npm run test:v3

      - name: Run e2e tests with tailwindcss v3
        run: npm run test:e2e

      - name: Install tailwindcss v4
        run: npm run install:v4

      - name: Run tests with tailwindcss v4
        run: npm run test:v4

      - name: Run e2e tests with tailwindcss v4
        run: npm run test:e2e

    strategy:
      fail-fast: true
      matrix:
        node:
          - 20
          - 22
          - 23
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
